# Generated by Django 5.1.3 on 2024-12-03 23:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_inmuebles', '0002_perfil'),
    ]

    operations = [
        migrations.AlterField(
            model_name='perfil',
            name='direccion',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='perfil',
            name='telefono',
            field=models.CharField(default='', max_length=15),
        ),
    ]
