# Generated by Django 5.1.3 on 2024-12-04 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_inmuebles', '0005_inmueble_imagen'),
    ]

    operations = [
        migrations.AddField(
            model_name='inmueble',
            name='imagen_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='inmueble',
            name='slug',
            field=models.SlugField(blank=True, null=True, unique=True),
        ),
    ]
