# Generated by Django 5.1.3 on 2024-12-04 12:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_inmuebles', '0006_inmueble_imagen_url_inmueble_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inmueble',
            name='imagen',
        ),
        migrations.RemoveField(
            model_name='inmueble',
            name='imagen_url',
        ),
        migrations.AlterField(
            model_name='inmueble',
            name='slug',
            field=models.SlugField(blank=True, default='1', unique=True),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='ImagenInmueble',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='inmuebles/')),
                ('imagen_url', models.URLField(blank=True, null=True)),
                ('inmueble', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='imagenes', to='gestion_inmuebles.inmueble')),
            ],
        ),
    ]
